FROM ros:jazzy-ros-base

# -------------------- ROS2 --------------------

RUN echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> ~/.bashrc

# -------------------- APT --------------------

RUN apt-get update && apt-get install -y \
    # gazebo
    ros-jazzy-ros-gz \    
    # ros2_control
    ros-jazzy-ros2-control \
    ros-jazzy-ros2-controllers \
    ros-jazzy-gz-ros2-control \
    # slam_toolbox
    ros-jazzy-slam-toolbox \
    # nav2
    ros-jazzy-navigation2 \
    ros-jazzy-nav2-bringup \
    # node_manager deps
    libboost-json-dev \
    libboost-thread-dev \
    && rm -rf /var/lib/apt/lists/*

# -------------------- waferbot_ros2_ws + node_manager --------------------

WORKDIR /root
COPY ../submodules/waferbot_ros2_ws waferbot_ros2_ws 
COPY ../submodules/node_manager ./waferbot_ros2_ws/src/node_manager

WORKDIR /root/waferbot_ros2_ws
RUN . /opt/ros/jazzy/setup.sh && colcon build --packages-select-regex "node_manager" "waferbot_*"
RUN echo "source ~/waferbot_ros2_ws/install/setup.bash" >> ~/.bashrc
