services:

  holonic-ros-tool:    
    build:
      context: .
      dockerfile: ./holonic-ros-tool/dockerfile
      pull: true
    image: holonic-ros-tool
    ports: # -p
      - 1880:1880 
    stdin_open: true # -i
    tty: true # -t
    command: bash

  sim-robot-demo:
    build:
      context: .
      dockerfile: ./sim-robot-demo/dockerfile
      pull: true
    image: sim-robot-demo
    # run on host "xhost +local:"
    environment: # -e
      - DISPLAY=${DISPLAY}
    volumes: # -v
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true # -i
    tty: true # -t
    command: bash
