FROM ros:jazzy

# generic deps
RUN apt-get update && apt-get install -y \
    python3-numpy \
    cython3 \
    python3-dev \
    python3-setuptools \
    python3-colcon-common-extensions \
    build-essential \ 
    cmake \
    iproute2 \ 
    iputils-ping

#-------------------------------------------------- ROS2 --------------------------------------------------
RUN echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> ~/.bashrc

# DDS Fix (so DDS does not try to communicate via IPC)
COPY fastdds_disable_ipc.xml /opt/ros/jazzy/fastdds_disable_ipc.xml
ENV FASTRTPS_DEFAULT_PROFILES_FILE=/opt/ros2/fastrtps/fastdds_disable_ipc.xml

# node-manager
RUN apt-get install -y libboost-json-dev libboost-thread-dev
WORKDIR /root/ros2_ws/src
RUN git clone https://github.com/xonder05/node_manager.git
WORKDIR /root/ros2_ws
RUN . /opt/ros/jazzy/setup.sh && colcon build
RUN echo "source ~/ros2_ws/install/setup.bash" >> ~/.bashrc

# Integration Service
RUN apt-get install -y libyaml-cpp-dev libboost-program-options-dev libwebsocketpp-dev \
                   libboost-system-dev libboost-dev libssl-dev libcurlpp-dev \
                   libasio-dev libcurl4-openssl-dev git

WORKDIR /root/is_ws/src
RUN git clone https://github.com/eProsima/Integration-Service.git is
RUN git clone https://github.com/eProsima/WebSocket-SH.git
RUN git clone https://github.com/eProsima/ROS2-SH.git
RUN sed -i '23a #include <cstdint>' ./is/core/include/is/utils/Log.hpp

WORKDIR /root/is_ws
RUN . /opt/ros/jazzy/setup.sh && colcon build --cmake-args -DIS_ROS2_SH_MODE=DYNAMIC --install-base /opt/is
RUN echo "source /opt/is/setup.bash" >> ~/.bashrc


#-------------------------------------------------- node.js --------------------------------------------------
WORKDIR /
RUN curl -sL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh
RUN chmod +x nodesource_setup.sh && sh -c ./nodesource_setup.sh
RUN apt-get install -y nodejs

# node-red
RUN npm install -g node-red

# custom nodes
WORKDIR /usr/lib/node_modules/node-red/node_modules
RUN git clone https://github.com/xonder05/node-red-custom-nodes.git

# is-web-api
WORKDIR /usr/lib/node_modules/node-red/node_modules/node-red-custom-nodes/node_modules
RUN git clone https://github.com/xonder05/is-web-api.git

WORKDIR /usr/lib/node_modules/node-red/node_modules/node-red-custom-nodes/node_modules/is-web-api
RUN npm install